/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as access from "../access.js";
import type * as accountRecovery from "../accountRecovery.js";
import type * as api_audience from "../api/audience.js";
import type * as api_automationGraph from "../api/automationGraph.js";
import type * as api_automations from "../api/automations.js";
import type * as api_broadcasts from "../api/broadcasts.js";
import type * as api_caller from "../api/caller.js";
import type * as api_calling from "../api/calling.js";
import type * as api_channelMessages from "../api/channelMessages.js";
import type * as api_domains from "../api/domains.js";
import type * as api_emailShares from "../api/emailShares.js";
import type * as api_emails from "../api/emails.js";
import type * as api_events from "../api/events.js";
import type * as api_http from "../api/http.js";
import type * as api_idempotency from "../api/idempotency.js";
import type * as api_imports from "../api/imports.js";
import type * as api_keys from "../api/keys.js";
import type * as api_logs from "../api/logs.js";
import type * as api_media from "../api/media.js";
import type * as api_metrics from "../api/metrics.js";
import type * as api_oauth from "../api/oauth.js";
import type * as api_paging from "../api/paging.js";
import type * as api_received from "../api/received.js";
import type * as api_route from "../api/route.js";
import type * as api_state from "../api/state.js";
import type * as api_suppressions from "../api/suppressions.js";
import type * as api_templates from "../api/templates.js";
import type * as api_usage from "../api/usage.js";
import type * as api_webhooks from "../api/webhooks.js";
import type * as api_whatsapp from "../api/whatsapp.js";
import type * as apiKeys from "../apiKeys.js";
import type * as audience from "../audience.js";
import type * as auth from "../auth.js";
import type * as authEmail from "../authEmail.js";
import type * as authHttp from "../authHttp.js";
import type * as authOptions from "../authOptions.js";
import type * as automationDefinition from "../automationDefinition.js";
import type * as automationEventOccurrenceRows from "../automationEventOccurrenceRows.js";
import type * as automationEventRows from "../automationEventRows.js";
import type * as automationEvents from "../automationEvents.js";
import type * as automationRuntime from "../automationRuntime.js";
import type * as automations from "../automations.js";
import type * as broadcastChannels from "../broadcastChannels.js";
import type * as broadcastEmail from "../broadcastEmail.js";
import type * as broadcastMetrics from "../broadcastMetrics.js";
import type * as broadcastSend from "../broadcastSend.js";
import type * as broadcastWhatsApp from "../broadcastWhatsApp.js";
import type * as broadcasts from "../broadcasts.js";
import type * as calling_agentAccess from "../calling/agentAccess.js";
import type * as calling_callActions from "../calling/callActions.js";
import type * as calling_gatewayHttp from "../calling/gatewayHttp.js";
import type * as calling_gatewayState from "../calling/gatewayState.js";
import type * as calling_media from "../calling/media.js";
import type * as calling_mediaState from "../calling/mediaState.js";
import type * as calling_projection from "../calling/projection.js";
import type * as calling_rows from "../calling/rows.js";
import type * as calling_settings from "../calling/settings.js";
import type * as calling_settingsState from "../calling/settingsState.js";
import type * as calling_softphone from "../calling/softphone.js";
import type * as calling_softphoneState from "../calling/softphoneState.js";
import type * as calling_values from "../calling/values.js";
import type * as channels_controlActions from "../channels/controlActions.js";
import type * as channels_controls from "../channels/controls.js";
import type * as channels_deliver from "../channels/deliver.js";
import type * as channels_downloads from "../channels/downloads.js";
import type * as channels_identity from "../channels/identity.js";
import type * as channels_media from "../channels/media.js";
import type * as channels_mediaState from "../channels/mediaState.js";
import type * as channels_mediaUpload from "../channels/mediaUpload.js";
import type * as channels_mediaUploads from "../channels/mediaUploads.js";
import type * as channels_messages from "../channels/messages.js";
import type * as channels_payload from "../channels/payload.js";
import type * as channels_rows from "../channels/rows.js";
import type * as channels_templates from "../channels/templates.js";
import type * as contactImports from "../contactImports.js";
import type * as contactProperties from "../contactProperties.js";
import type * as contacts from "../contacts.js";
import type * as conversations from "../conversations.js";
import type * as counts from "../counts.js";
import type * as crons from "../crons.js";
import type * as domainClaims from "../domainClaims.js";
import type * as domains from "../domains.js";
import type * as email_render from "../email/render.js";
import type * as emailAttachments from "../emailAttachments.js";
import type * as emailRows from "../emailRows.js";
import type * as emailSend from "../emailSend.js";
import type * as emailShares from "../emailShares.js";
import type * as emails from "../emails.js";
import type * as events from "../events.js";
import type * as exportRows from "../exportRows.js";
import type * as exportSources from "../exportSources.js";
import type * as exports from "../exports.js";
import type * as fileDownloads from "../fileDownloads.js";
import type * as http from "../http.js";
import type * as installation from "../installation.js";
import type * as installationActions from "../installationActions.js";
import type * as installationAdmin from "../installationAdmin.js";
import type * as lists from "../lists.js";
import type * as logs from "../logs.js";
import type * as messages from "../messages.js";
import type * as meta_app from "../meta/app.js";
import type * as meta_appActions from "../meta/appActions.js";
import type * as meta_connect from "../meta/connect.js";
import type * as meta_connectActions from "../meta/connectActions.js";
import type * as meta_fixtures from "../meta/fixtures.js";
import type * as meta_graph from "../meta/graph.js";
import type * as meta_http from "../meta/http.js";
import type * as meta_ingest from "../meta/ingest.js";
import type * as meta_pageConnectActions from "../meta/pageConnectActions.js";
import type * as meta_pageState from "../meta/pageState.js";
import type * as meta_projection from "../meta/projection.js";
import type * as metricRows from "../metricRows.js";
import type * as metrics from "../metrics.js";
import type * as migrations from "../migrations.js";
import type * as oauth from "../oauth.js";
import type * as oauthAdapter from "../oauthAdapter.js";
import type * as oauthAdmin from "../oauthAdmin.js";
import type * as oauthHttp from "../oauthHttp.js";
import type * as oauthProvider from "../oauthProvider.js";
import type * as oidc from "../oidc.js";
import type * as publicHttp from "../publicHttp.js";
import type * as received from "../received.js";
import type * as receivedDownloads from "../receivedDownloads.js";
import type * as receivedParse from "../receivedParse.js";
import type * as retention from "../retention.js";
import type * as secrets from "../secrets.js";
import type * as segments from "../segments.js";
import type * as ses_adoption from "../ses/adoption.js";
import type * as ses_aws from "../ses/aws.js";
import type * as ses_claimDns from "../ses/claimDns.js";
import type * as ses_contracts from "../ses/contracts.js";
import type * as ses_crypto from "../ses/crypto.js";
import type * as ses_dns from "../ses/dns.js";
import type * as ses_dnsProvider from "../ses/dnsProvider.js";
import type * as ses_domainConnect from "../ses/domainConnect.js";
import type * as ses_events from "../ses/events.js";
import type * as ses_http from "../ses/http.js";
import type * as ses_inbound from "../ses/inbound.js";
import type * as ses_inboundMessages from "../ses/inboundMessages.js";
import type * as ses_inboundRegions from "../ses/inboundRegions.js";
import type * as ses_inboundTransfer from "../ses/inboundTransfer.js";
import type * as ses_limits from "../ses/limits.js";
import type * as ses_pacing from "../ses/pacing.js";
import type * as ses_projection from "../ses/projection.js";
import type * as ses_provision from "../ses/provision.js";
import type * as ses_records from "../ses/records.js";
import type * as ses_reputation from "../ses/reputation.js";
import type * as ses_reputationActions from "../ses/reputationActions.js";
import type * as ses_sendContext from "../ses/sendContext.js";
import type * as ses_sns from "../ses/sns.js";
import type * as ses_state from "../ses/state.js";
import type * as ses_tenantActions from "../ses/tenantActions.js";
import type * as ses_tenantProvider from "../ses/tenantProvider.js";
import type * as ses_topics from "../ses/topics.js";
import type * as ses_verify from "../ses/verify.js";
import type * as ses_web from "../ses/web.js";
import type * as ses_workflows from "../ses/workflows.js";
import type * as smtp from "../smtp.js";
import type * as smtpHttp from "../smtpHttp.js";
import type * as sso from "../sso.js";
import type * as storage_assets from "../storage/assets.js";
import type * as storage_files from "../storage/files.js";
import type * as storage_media from "../storage/media.js";
import type * as storage_objects from "../storage/objects.js";
import type * as storage_urls from "../storage/urls.js";
import type * as suppressions from "../suppressions.js";
import type * as systemEmail from "../systemEmail.js";
import type * as tables_api from "../tables/api.js";
import type * as tables_audience from "../tables/audience.js";
import type * as tables_automationEvents from "../tables/automationEvents.js";
import type * as tables_automations from "../tables/automations.js";
import type * as tables_broadcasts from "../tables/broadcasts.js";
import type * as tables_channels from "../tables/channels.js";
import type * as tables_domainClaims from "../tables/domainClaims.js";
import type * as tables_domains from "../tables/domains.js";
import type * as tables_emailShares from "../tables/emailShares.js";
import type * as tables_emails from "../tables/emails.js";
import type * as tables_events from "../tables/events.js";
import type * as tables_exports from "../tables/exports.js";
import type * as tables_meta from "../tables/meta.js";
import type * as tables_metrics from "../tables/metrics.js";
import type * as tables_received from "../tables/received.js";
import type * as tables_receiving from "../tables/receiving.js";
import type * as tables_ses from "../tables/ses.js";
import type * as tables_smtp from "../tables/smtp.js";
import type * as tables_storage from "../tables/storage.js";
import type * as tables_teams from "../tables/teams.js";
import type * as tables_templates from "../tables/templates.js";
import type * as tables_unsubscribe from "../tables/unsubscribe.js";
import type * as tables_variables from "../tables/variables.js";
import type * as tables_webhooks from "../tables/webhooks.js";
import type * as teamCleanup from "../teamCleanup.js";
import type * as teamLifecycle from "../teamLifecycle.js";
import type * as teams from "../teams.js";
import type * as templateChannels from "../templateChannels.js";
import type * as templates from "../templates.js";
import type * as tenants from "../tenants.js";
import type * as testEmails from "../testEmails.js";
import type * as testHelpers_snsFixture from "../testHelpers/snsFixture.js";
import type * as topics from "../topics.js";
import type * as tracking from "../tracking.js";
import type * as trackingHttp from "../trackingHttp.js";
import type * as unsubscribe from "../unsubscribe.js";
import type * as unsubscribeHttp from "../unsubscribeHttp.js";
import type * as usage from "../usage.js";
import type * as webhookDelivery from "../webhookDelivery.js";
import type * as webhooks from "../webhooks.js";
import type * as whatsapp_rows from "../whatsapp/rows.js";
import type * as whatsapp_templateActions from "../whatsapp/templateActions.js";
import type * as whatsapp_templates from "../whatsapp/templates.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  access: typeof access;
  accountRecovery: typeof accountRecovery;
  "api/audience": typeof api_audience;
  "api/automationGraph": typeof api_automationGraph;
  "api/automations": typeof api_automations;
  "api/broadcasts": typeof api_broadcasts;
  "api/caller": typeof api_caller;
  "api/calling": typeof api_calling;
  "api/channelMessages": typeof api_channelMessages;
  "api/domains": typeof api_domains;
  "api/emailShares": typeof api_emailShares;
  "api/emails": typeof api_emails;
  "api/events": typeof api_events;
  "api/http": typeof api_http;
  "api/idempotency": typeof api_idempotency;
  "api/imports": typeof api_imports;
  "api/keys": typeof api_keys;
  "api/logs": typeof api_logs;
  "api/media": typeof api_media;
  "api/metrics": typeof api_metrics;
  "api/oauth": typeof api_oauth;
  "api/paging": typeof api_paging;
  "api/received": typeof api_received;
  "api/route": typeof api_route;
  "api/state": typeof api_state;
  "api/suppressions": typeof api_suppressions;
  "api/templates": typeof api_templates;
  "api/usage": typeof api_usage;
  "api/webhooks": typeof api_webhooks;
  "api/whatsapp": typeof api_whatsapp;
  apiKeys: typeof apiKeys;
  audience: typeof audience;
  auth: typeof auth;
  authEmail: typeof authEmail;
  authHttp: typeof authHttp;
  authOptions: typeof authOptions;
  automationDefinition: typeof automationDefinition;
  automationEventOccurrenceRows: typeof automationEventOccurrenceRows;
  automationEventRows: typeof automationEventRows;
  automationEvents: typeof automationEvents;
  automationRuntime: typeof automationRuntime;
  automations: typeof automations;
  broadcastChannels: typeof broadcastChannels;
  broadcastEmail: typeof broadcastEmail;
  broadcastMetrics: typeof broadcastMetrics;
  broadcastSend: typeof broadcastSend;
  broadcastWhatsApp: typeof broadcastWhatsApp;
  broadcasts: typeof broadcasts;
  "calling/agentAccess": typeof calling_agentAccess;
  "calling/callActions": typeof calling_callActions;
  "calling/gatewayHttp": typeof calling_gatewayHttp;
  "calling/gatewayState": typeof calling_gatewayState;
  "calling/media": typeof calling_media;
  "calling/mediaState": typeof calling_mediaState;
  "calling/projection": typeof calling_projection;
  "calling/rows": typeof calling_rows;
  "calling/settings": typeof calling_settings;
  "calling/settingsState": typeof calling_settingsState;
  "calling/softphone": typeof calling_softphone;
  "calling/softphoneState": typeof calling_softphoneState;
  "calling/values": typeof calling_values;
  "channels/controlActions": typeof channels_controlActions;
  "channels/controls": typeof channels_controls;
  "channels/deliver": typeof channels_deliver;
  "channels/downloads": typeof channels_downloads;
  "channels/identity": typeof channels_identity;
  "channels/media": typeof channels_media;
  "channels/mediaState": typeof channels_mediaState;
  "channels/mediaUpload": typeof channels_mediaUpload;
  "channels/mediaUploads": typeof channels_mediaUploads;
  "channels/messages": typeof channels_messages;
  "channels/payload": typeof channels_payload;
  "channels/rows": typeof channels_rows;
  "channels/templates": typeof channels_templates;
  contactImports: typeof contactImports;
  contactProperties: typeof contactProperties;
  contacts: typeof contacts;
  conversations: typeof conversations;
  counts: typeof counts;
  crons: typeof crons;
  domainClaims: typeof domainClaims;
  domains: typeof domains;
  "email/render": typeof email_render;
  emailAttachments: typeof emailAttachments;
  emailRows: typeof emailRows;
  emailSend: typeof emailSend;
  emailShares: typeof emailShares;
  emails: typeof emails;
  events: typeof events;
  exportRows: typeof exportRows;
  exportSources: typeof exportSources;
  exports: typeof exports;
  fileDownloads: typeof fileDownloads;
  http: typeof http;
  installation: typeof installation;
  installationActions: typeof installationActions;
  installationAdmin: typeof installationAdmin;
  lists: typeof lists;
  logs: typeof logs;
  messages: typeof messages;
  "meta/app": typeof meta_app;
  "meta/appActions": typeof meta_appActions;
  "meta/connect": typeof meta_connect;
  "meta/connectActions": typeof meta_connectActions;
  "meta/fixtures": typeof meta_fixtures;
  "meta/graph": typeof meta_graph;
  "meta/http": typeof meta_http;
  "meta/ingest": typeof meta_ingest;
  "meta/pageConnectActions": typeof meta_pageConnectActions;
  "meta/pageState": typeof meta_pageState;
  "meta/projection": typeof meta_projection;
  metricRows: typeof metricRows;
  metrics: typeof metrics;
  migrations: typeof migrations;
  oauth: typeof oauth;
  oauthAdapter: typeof oauthAdapter;
  oauthAdmin: typeof oauthAdmin;
  oauthHttp: typeof oauthHttp;
  oauthProvider: typeof oauthProvider;
  oidc: typeof oidc;
  publicHttp: typeof publicHttp;
  received: typeof received;
  receivedDownloads: typeof receivedDownloads;
  receivedParse: typeof receivedParse;
  retention: typeof retention;
  secrets: typeof secrets;
  segments: typeof segments;
  "ses/adoption": typeof ses_adoption;
  "ses/aws": typeof ses_aws;
  "ses/claimDns": typeof ses_claimDns;
  "ses/contracts": typeof ses_contracts;
  "ses/crypto": typeof ses_crypto;
  "ses/dns": typeof ses_dns;
  "ses/dnsProvider": typeof ses_dnsProvider;
  "ses/domainConnect": typeof ses_domainConnect;
  "ses/events": typeof ses_events;
  "ses/http": typeof ses_http;
  "ses/inbound": typeof ses_inbound;
  "ses/inboundMessages": typeof ses_inboundMessages;
  "ses/inboundRegions": typeof ses_inboundRegions;
  "ses/inboundTransfer": typeof ses_inboundTransfer;
  "ses/limits": typeof ses_limits;
  "ses/pacing": typeof ses_pacing;
  "ses/projection": typeof ses_projection;
  "ses/provision": typeof ses_provision;
  "ses/records": typeof ses_records;
  "ses/reputation": typeof ses_reputation;
  "ses/reputationActions": typeof ses_reputationActions;
  "ses/sendContext": typeof ses_sendContext;
  "ses/sns": typeof ses_sns;
  "ses/state": typeof ses_state;
  "ses/tenantActions": typeof ses_tenantActions;
  "ses/tenantProvider": typeof ses_tenantProvider;
  "ses/topics": typeof ses_topics;
  "ses/verify": typeof ses_verify;
  "ses/web": typeof ses_web;
  "ses/workflows": typeof ses_workflows;
  smtp: typeof smtp;
  smtpHttp: typeof smtpHttp;
  sso: typeof sso;
  "storage/assets": typeof storage_assets;
  "storage/files": typeof storage_files;
  "storage/media": typeof storage_media;
  "storage/objects": typeof storage_objects;
  "storage/urls": typeof storage_urls;
  suppressions: typeof suppressions;
  systemEmail: typeof systemEmail;
  "tables/api": typeof tables_api;
  "tables/audience": typeof tables_audience;
  "tables/automationEvents": typeof tables_automationEvents;
  "tables/automations": typeof tables_automations;
  "tables/broadcasts": typeof tables_broadcasts;
  "tables/channels": typeof tables_channels;
  "tables/domainClaims": typeof tables_domainClaims;
  "tables/domains": typeof tables_domains;
  "tables/emailShares": typeof tables_emailShares;
  "tables/emails": typeof tables_emails;
  "tables/events": typeof tables_events;
  "tables/exports": typeof tables_exports;
  "tables/meta": typeof tables_meta;
  "tables/metrics": typeof tables_metrics;
  "tables/received": typeof tables_received;
  "tables/receiving": typeof tables_receiving;
  "tables/ses": typeof tables_ses;
  "tables/smtp": typeof tables_smtp;
  "tables/storage": typeof tables_storage;
  "tables/teams": typeof tables_teams;
  "tables/templates": typeof tables_templates;
  "tables/unsubscribe": typeof tables_unsubscribe;
  "tables/variables": typeof tables_variables;
  "tables/webhooks": typeof tables_webhooks;
  teamCleanup: typeof teamCleanup;
  teamLifecycle: typeof teamLifecycle;
  teams: typeof teams;
  templateChannels: typeof templateChannels;
  templates: typeof templates;
  tenants: typeof tenants;
  testEmails: typeof testEmails;
  "testHelpers/snsFixture": typeof testHelpers_snsFixture;
  topics: typeof topics;
  tracking: typeof tracking;
  trackingHttp: typeof trackingHttp;
  unsubscribe: typeof unsubscribe;
  unsubscribeHttp: typeof unsubscribeHttp;
  usage: typeof usage;
  webhookDelivery: typeof webhookDelivery;
  webhooks: typeof webhooks;
  "whatsapp/rows": typeof whatsapp_rows;
  "whatsapp/templateActions": typeof whatsapp_templateActions;
  "whatsapp/templates": typeof whatsapp_templates;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  inboundPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"inboundPool">;
  sendPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"sendPool">;
  webhookPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"webhookPool">;
  channelPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"channelPool">;
  contactImportCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"contactImportCounts">;
  contactCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"contactCounts">;
  segmentCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"segmentCounts">;
  segmentMemberCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"segmentMemberCounts">;
  topicCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"topicCounts">;
  propertyCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"propertyCounts">;
  templateCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"templateCounts">;
  apiKeyCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"apiKeyCounts">;
  apiLogCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"apiLogCounts">;
  apiKeyLogCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"apiKeyLogCounts">;
  webhookCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"webhookCounts">;
  deliveryCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"deliveryCounts">;
  webhookAttemptCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"webhookAttemptCounts">;
  domainCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"domainCounts">;
  exportCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"exportCounts">;
  emailCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"emailCounts">;
  suppressionCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"suppressionCounts">;
  emailRecipientCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"emailRecipientCounts">;
  emailEventCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"emailEventCounts">;
  emailDomainCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"emailDomainCounts">;
  emailMetricCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"emailMetricCounts">;
  domainMetricCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"domainMetricCounts">;
  reputationCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"reputationCounts">;
  automationCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"automationCounts">;
  automationRunCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"automationRunCounts">;
  automationStepCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"automationStepCounts">;
  receivedEmailCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"receivedEmailCounts">;
  broadcastCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"broadcastCounts">;
  broadcastRecipientCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"broadcastRecipientCounts">;
  broadcastHistoryCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"broadcastHistoryCounts">;
  broadcastEventCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"broadcastEventCounts">;
  broadcastLinkCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"broadcastLinkCounts">;
  broadcastRecipientLinkCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"broadcastRecipientLinkCounts">;
  usageSentCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usageSentCounts">;
  usageReceivedCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usageReceivedCounts">;
  usageAutomationCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usageAutomationCounts">;
  channelMessageCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"channelMessageCounts">;
  conversationCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"conversationCounts">;
  broadcastMessageCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"broadcastMessageCounts">;
  channelAccountCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"channelAccountCounts">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
};
